# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the
# first terms will be:
#           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

def solution(limit: int):
    prev = 0
    curr = 1
    s = 0
    while curr <= limit:
        if curr % 2 == 0:
            s += curr
        nxt = curr + prev
        prev = curr
        curr = nxt
    return s


print(solution(4_000_000))
